/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmail_renanfr1047_FootballChant */

#ifndef _Included_com_gmail_renanfr1047_FootballChant
#define _Included_com_gmail_renanfr1047_FootballChant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gmail_renanfr1047_FootballChant
 * Method:    chant
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_renanfr1047_FootballChant_chant
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
