/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Native */

#ifndef _Included_com_example_Native
#define _Included_com_example_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Native
 * Method:    addNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_Native_addNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
